language: python
sudo: true
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - "virtualenv venv --no-site-packages"
  - "source venv/bin/activate"
  - sudo apt-get install silversearcher-ag
  - pip install --upgrade pip setuptools
  - pip install --force-reinstall twine==1.12.1
  - pip install .
script:
  - configcat-validator.py PKDVCLf-Hq-h-kCzMp-L7Q/NB1-IBFV50erQbSn7DXGIw ./sample_to_scan -v
deploy:
  provider: pypi
  twine_version: 1.12.1
  user: "$PYPI_USERNAME"
  password: "$PYPI_PASSWORD"
  skip_existing: true
  skip_cleanup: true
  edge: true
  on:
    tags: true
    branch: master
    python: 2.7

