version: 2.1
description: |
  Job and commands for discovering ConfigCat feature flag usages in your source
  code and validating them against your own ConfigCat configuration dashboard.

display:
  home_url: https://configcat.com
  source_url: https://github.com/configcat/flag-reference-validator

examples:
  job-default-configuration:
    description: Executes the reference validatior job with default parameters.
    usage:
      version: 2.1
      orbs:
        configcat: configcat/feature-flag-reference-validator@1.1
      workflows:
        main:
          jobs:
            - configcat/validate-flag-references

  job-complex-configuration:
    description: Executes the reference validatior job with verbose logging and fails the execution on validation warnings.
    usage:
      version: 2.1
      orbs:
        configcat: configcat/feature-flag-reference-validator@1.1
      workflows:
        main:
          jobs:
            - configcat/validate-flag-references:
                debug: true
                fail-on-warnings: true

  install-validator-command:
    description: Installs the ConfigCat validator and it's dependencies on the current environment. It uses `apt-get` and `pip` so it must be executed on an environment which has those.
    usage:
      version: 2.1
      orbs:
        configcat: configcat/feature-flag-reference-validator@1.1
      jobs:
        build:
          docker:
            - image: circleci/python:2.7
          steps:
            - configcat/install-validator

  execute-validation-command:
    description: Installs the ConfigCat validator and executes the reference validation command with custom configuration on a python based docker environment.
    usage:
      version: 2.1
      orbs:
        configcat: configcat/feature-flag-reference-validator@1.1
      jobs:
        build:
          docker:
            - image: circleci/python:2.7
          steps:
            - checkout:
                path: /repo
            - configcat/install-validator
            - configcat/execute-validation:
                debug: true
                fail-on-warnings: true
                scan-directory: /repo

  custom-executor:
    description: Executes the reference validatior in a job which uses the preconfigured configcat job executor.
    usage:
      version: 2.1
      orbs:
        configcat: configcat/feature-flag-reference-validator@1.1
      jobs:
        build:
          executor: configcat/default
          steps:
            - checkout
            - configcat/execute-validation

executors:
  default:
    description: The Docker container to use when executing the reference validator job.
    parameters:
      docker-image-version:
        description: The version of the ConfigCat flag reference validator docker image.
        type: string
        default: 1.1.0
    docker:
      - image: configcat/feature-flag-reference-validator:<< parameters.docker-image-version >>

commands:
  install-validator:
    description: Installs the ConfigCat flag reference validator tool and its dependencies.
    parameters:
      validator-version:
        description: The version of the ConfigCat flag reference validator pypi package.
        type: string
        default: 1.1.0
    steps:
    - run:
        name: Install feature flag validator dependencies
        command: sudo apt-get install silversearcher-ag
    - run:
        name: Install feature flag reference validator
        command: sudo pip install configcat-flag-reference-validator==<< parameters.validator-version >>

  install-validator-win:
    description: Installs the ConfigCat flag reference validator tool and its dependencies on windows.
    parameters:
      validator-version:
        description: The version of the ConfigCat flag reference validator pypi package.
        type: string
        default: 1.1.0
    steps:
    - run:
        name: Install feature flag reference validator dependencies
        shell: powershell.exe
        command: |
          choco install python --no-progress
          choco install ag --no-progress
    - run:
        name: Install feature flag reference validator
        shell: powershell.exe
        command: pip install configcat-flag-reference-validator==<< parameters.validator-version >>

  execute-validation:
    description: Scans the repository for ConfigCat feature flag references. Displays the missing feature flag keys in CircleCI's build log.
    parameters:
      configcat-api-key:
        description: The api key of your ConfigCat project.
        default: CONFIG_CAT_API_KEY
        type: env_var_name
      scan-directory:
        description: The directory to scan for flag references.
        type: string
        default: .
      configcat-cdn-server:
        description: The domain name of the ConfigCat CDN where you ConfigCat configuration file is stored.
        type: string
        default: cdn.configcat.com
      fail-on-warnings:
        description: Signals a build error in CircleCI when the validation fails. By default only warnings are showed.
        type: boolean
        default: false
      debug:
        description: Turns on detailed logging.
        type: boolean
        default: false
    steps:
    - run:
        name: Scanning code for unused feature flags
        command: |
          if [[ -z "${<< parameters.configcat-api-key >>}" ]]; then
            echo "Please, set the environemnt variable: '<< parameters.configcat-api-key >>'. Will stop now."
            exit 1
          fi
          configcat-validator.py ${<< parameters.configcat-api-key >>} << parameters.scan-directory >> -s="<< parameters.configcat-cdn-server >>" -v=<< parameters.debug >> -f=<< parameters.fail-on-warnings >>

  execute-validation-win:
    description: Scans the repository for ConfigCat feature flag references on windows. Displays the missing feature flag keys in CircleCI's build log.
    parameters:
      configcat-api-key:
        description: The api key of your ConfigCat project.
        default: CONFIG_CAT_API_KEY
        type: env_var_name
      scan-directory:
        description: The directory to scan for flag references.
        type: string
        default: .
      configcat-cdn-server:
        description: The domain name of the ConfigCat CDN where you ConfigCat configuration file is stored.
        type: string
        default: cdn.configcat.com
      fail-on-warnings:
        description: Signals a build error in CircleCI when the validation fails. By default only warnings are showed.
        type: boolean
        default: false
      debug:
        description: Turns on detailed logging.
        type: boolean
        default: false
    steps:
    - run:
        name: Scanning code for unused feature flags
        shell: powershell.exe
        command: |
          if (-not (Test-Path env:<< parameters.configcat-api-key >>)) {
            Write-Host "Please, set the environemnt variable: '<< parameters.configcat-api-key >>'. Will stop now."
            exit 1
          }
          configcat-validator.py $env:<< parameters.configcat-api-key >> << parameters.scan-directory >> -s="<< parameters.configcat-cdn-server >>" -v=<< parameters.debug >> -f=<< parameters.fail-on-warnings >>

jobs:
  validate-flag-references:
    description: Scans the repository for ConfigCat feature flag references. Displays the missing feature flag keys in CircleCI's build log.
    parameters:
      configcat-api-key:
        description: The api key of your ConfigCat project.
        default: CONFIG_CAT_API_KEY
        type: env_var_name
      configcat-cdn-server:
        description: The domain name of the ConfigCat CDN where you ConfigCat configuration file is stored.
        type: string
        default: cdn.configcat.com
      fail-on-warnings:
        description: Signals a build error in CircleCI when the validation fails. By default only warnings are showed.
        type: boolean
        default: false
      debug:
        description: Turns on detailed logging.
        type: boolean
        default: false
    executor:
      name: default
    working_directory: /ref-validator
    steps:
      - checkout:
          path: /ref-validator/repo
      - execute-validation:
          configcat-api-key: << parameters.configcat-api-key >>
          configcat-cdn-server: << parameters.configcat-cdn-server >>
          fail-on-warnings: << parameters.fail-on-warnings >>
          debug: << parameters.debug >>
          scan-directory: ./repo
